# Generated by Django 4.2.1 on 2023-05-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={'verbose_name_plural': 'User'},
        ),
    ]
