# Generated by Django 4.2.1 on 2023-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_userauth_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauth",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
